[build]
  base = "client"
  publish = "dist"
  command = "npm ci && npm run build"

# SPA redirect to index.html so React Router routes work on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
